import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Home from "@/app/page";
import Header from "@/app/header";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className={"h-full"}>
            <Header/>
            <Home/>
        </div>
        </body>
        </html>
    )
}
